# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1437, 825)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(parent=self.page)
        self.frame.setGeometry(QtCore.QRect(470, 30, 601, 121))
        self.frame.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(209, 209, 209);\n"
"    border-radius: 10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.welcome_label = QtWidgets.QLabel(parent=self.frame)
        self.welcome_label.setGeometry(QtCore.QRect(80, 30, 661, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_label.setFont(font)
        self.welcome_label.setObjectName("welcome_label")
        self.frame_2 = QtWidgets.QFrame(parent=self.page)
        self.frame_2.setGeometry(QtCore.QRect(50, 220, 661, 531))
        self.frame_2.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(209, 209, 209);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.welcome_label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.welcome_label_2.setGeometry(QtCore.QRect(210, 20, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_label_2.setFont(font)
        self.welcome_label_2.setObjectName("welcome_label_2")
        self.pg1_addition_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.pg1_addition_btn.setGeometry(QtCore.QRect(210, 130, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pg1_addition_btn.setFont(font)
        self.pg1_addition_btn.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(12, 44, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    background-color: rgb(0, 2, 147);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(75, 192, 255);\n"
"}\n"
"")
        self.pg1_addition_btn.setObjectName("pg1_addition_btn")
        self.pg1_subtraction_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.pg1_subtraction_btn.setGeometry(QtCore.QRect(210, 220, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pg1_subtraction_btn.setFont(font)
        self.pg1_subtraction_btn.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(12, 44, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    background-color: rgb(0, 2, 147);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(75, 192, 255);\n"
"}\n"
"")
        self.pg1_subtraction_btn.setObjectName("pg1_subtraction_btn")
        self.pg1_multi_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.pg1_multi_btn.setGeometry(QtCore.QRect(210, 310, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pg1_multi_btn.setFont(font)
        self.pg1_multi_btn.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(12, 44, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    background-color: rgb(0, 2, 147);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(75, 192, 255);\n"
"}\n"
"")
        self.pg1_multi_btn.setObjectName("pg1_multi_btn")
        self.pg1_division_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.pg1_division_btn.setGeometry(QtCore.QRect(210, 400, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pg1_division_btn.setFont(font)
        self.pg1_division_btn.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(12, 44, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    background-color: rgb(0, 2, 147);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(75, 192, 255);\n"
"}\n"
"")
        self.pg1_division_btn.setObjectName("pg1_division_btn")
        self.frame_3 = QtWidgets.QFrame(parent=self.page)
        self.frame_3.setGeometry(QtCore.QRect(810, 220, 661, 531))
        self.frame_3.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(209, 209, 209);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_4 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_4.setGeometry(QtCore.QRect(520, 0, 601, 121))
        self.frame_4.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(209, 209, 209);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.head_label = QtWidgets.QLabel(parent=self.frame_4)
        self.head_label.setGeometry(QtCore.QRect(80, 30, 661, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.head_label.setFont(font)
        self.head_label.setObjectName("head_label")
        self.frame_5 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_5.setGeometry(QtCore.QRect(30, 140, 221, 301))
        self.frame_5.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(209, 209, 209);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.welcome_label_5 = QtWidgets.QLabel(parent=self.frame_5)
        self.welcome_label_5.setGeometry(QtCore.QRect(40, 10, 151, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_label_5.setFont(font)
        self.welcome_label_5.setObjectName("welcome_label_5")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_5)
        self.lineEdit.setGeometry(QtCore.QRect(30, 160, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.head_label_2 = QtWidgets.QLabel(parent=self.frame_5)
        self.head_label_2.setGeometry(QtCore.QRect(30, 240, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.head_label_2.setFont(font)
        self.head_label_2.setObjectName("head_label_2")
        self.frame_7 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_7.setGeometry(QtCore.QRect(30, 470, 221, 301))
        self.frame_7.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(209, 209, 209);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.welcome_label_8 = QtWidgets.QLabel(parent=self.frame_7)
        self.welcome_label_8.setGeometry(QtCore.QRect(40, 10, 151, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_label_8.setFont(font)
        self.welcome_label_8.setObjectName("welcome_label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.frame_7)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 160, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.head_label_3 = QtWidgets.QLabel(parent=self.frame_7)
        self.head_label_3.setGeometry(QtCore.QRect(20, 240, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.head_label_3.setFont(font)
        self.head_label_3.setObjectName("head_label_3")
        self.frame_13 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_13.setGeometry(QtCore.QRect(930, 470, 221, 301))
        self.frame_13.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(209, 209, 209);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.welcome_label_15 = QtWidgets.QLabel(parent=self.frame_13)
        self.welcome_label_15.setGeometry(QtCore.QRect(20, 10, 171, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_label_15.setFont(font)
        self.welcome_label_15.setObjectName("welcome_label_15")
        self.lineEdit_11 = QtWidgets.QLineEdit(parent=self.frame_13)
        self.lineEdit_11.setGeometry(QtCore.QRect(30, 160, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.head_label_15 = QtWidgets.QLabel(parent=self.frame_13)
        self.head_label_15.setGeometry(QtCore.QRect(10, 240, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.head_label_15.setFont(font)
        self.head_label_15.setObjectName("head_label_15")
        self.pg1_addition_btn_2 = QtWidgets.QPushButton(parent=self.page_2)
        self.pg1_addition_btn_2.setGeometry(QtCore.QRect(1190, 490, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pg1_addition_btn_2.setFont(font)
        self.pg1_addition_btn_2.setStyleSheet(" QPushButton {\n"
"    \n"
"    background-color: rgb(255, 230, 44);\n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    \n"
"    \n"
"    background-color: rgb(255, 183, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    \n"
"    background-color: rgb(255, 240, 153);\n"
"}\n"
"")
        self.pg1_addition_btn_2.setObjectName("pg1_addition_btn_2")
        self.frame_6 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_6.setGeometry(QtCore.QRect(330, 140, 221, 301))
        self.frame_6.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(209, 209, 209);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.welcome_label_7 = QtWidgets.QLabel(parent=self.frame_6)
        self.welcome_label_7.setGeometry(QtCore.QRect(40, 10, 151, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_label_7.setFont(font)
        self.welcome_label_7.setObjectName("welcome_label_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame_6)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 160, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.head_label_4 = QtWidgets.QLabel(parent=self.frame_6)
        self.head_label_4.setGeometry(QtCore.QRect(30, 240, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.head_label_4.setFont(font)
        self.head_label_4.setObjectName("head_label_4")
        self.frame_9 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_9.setGeometry(QtCore.QRect(630, 140, 221, 301))
        self.frame_9.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(209, 209, 209);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.welcome_label_12 = QtWidgets.QLabel(parent=self.frame_9)
        self.welcome_label_12.setGeometry(QtCore.QRect(40, 10, 151, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_label_12.setFont(font)
        self.welcome_label_12.setObjectName("welcome_label_12")
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.frame_9)
        self.lineEdit_8.setGeometry(QtCore.QRect(30, 160, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.head_label_7 = QtWidgets.QLabel(parent=self.frame_9)
        self.head_label_7.setGeometry(QtCore.QRect(30, 240, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.head_label_7.setFont(font)
        self.head_label_7.setObjectName("head_label_7")
        self.frame_10 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_10.setGeometry(QtCore.QRect(930, 140, 221, 301))
        self.frame_10.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(209, 209, 209);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.welcome_label_16 = QtWidgets.QLabel(parent=self.frame_10)
        self.welcome_label_16.setGeometry(QtCore.QRect(40, 10, 151, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_label_16.setFont(font)
        self.welcome_label_16.setObjectName("welcome_label_16")
        self.lineEdit_12 = QtWidgets.QLineEdit(parent=self.frame_10)
        self.lineEdit_12.setGeometry(QtCore.QRect(30, 160, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.head_label_8 = QtWidgets.QLabel(parent=self.frame_10)
        self.head_label_8.setGeometry(QtCore.QRect(30, 240, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.head_label_8.setFont(font)
        self.head_label_8.setObjectName("head_label_8")
        self.frame_11 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_11.setGeometry(QtCore.QRect(1230, 140, 221, 301))
        self.frame_11.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(209, 209, 209);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.welcome_label_17 = QtWidgets.QLabel(parent=self.frame_11)
        self.welcome_label_17.setGeometry(QtCore.QRect(40, 10, 151, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_label_17.setFont(font)
        self.welcome_label_17.setObjectName("welcome_label_17")
        self.lineEdit_13 = QtWidgets.QLineEdit(parent=self.frame_11)
        self.lineEdit_13.setGeometry(QtCore.QRect(30, 160, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.head_label_9 = QtWidgets.QLabel(parent=self.frame_11)
        self.head_label_9.setGeometry(QtCore.QRect(30, 240, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.head_label_9.setFont(font)
        self.head_label_9.setObjectName("head_label_9")
        self.frame_8 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_8.setGeometry(QtCore.QRect(330, 470, 221, 301))
        self.frame_8.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(209, 209, 209);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.welcome_label_13 = QtWidgets.QLabel(parent=self.frame_8)
        self.welcome_label_13.setGeometry(QtCore.QRect(40, 10, 151, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_label_13.setFont(font)
        self.welcome_label_13.setObjectName("welcome_label_13")
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.frame_8)
        self.lineEdit_9.setGeometry(QtCore.QRect(30, 160, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.head_label_11 = QtWidgets.QLabel(parent=self.frame_8)
        self.head_label_11.setGeometry(QtCore.QRect(20, 240, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.head_label_11.setFont(font)
        self.head_label_11.setObjectName("head_label_11")
        self.frame_12 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_12.setGeometry(QtCore.QRect(630, 470, 221, 301))
        self.frame_12.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(209, 209, 209);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.welcome_label_19 = QtWidgets.QLabel(parent=self.frame_12)
        self.welcome_label_19.setGeometry(QtCore.QRect(40, 10, 151, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_label_19.setFont(font)
        self.welcome_label_19.setObjectName("welcome_label_19")
        self.lineEdit_15 = QtWidgets.QLineEdit(parent=self.frame_12)
        self.lineEdit_15.setGeometry(QtCore.QRect(30, 160, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.head_label_14 = QtWidgets.QLabel(parent=self.frame_12)
        self.head_label_14.setGeometry(QtCore.QRect(20, 240, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.head_label_14.setFont(font)
        self.head_label_14.setObjectName("head_label_14")
        self.pg1_addition_btn_3 = QtWidgets.QPushButton(parent=self.page_2)
        self.pg1_addition_btn_3.setGeometry(QtCore.QRect(1190, 590, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pg1_addition_btn_3.setFont(font)
        self.pg1_addition_btn_3.setStyleSheet(" QPushButton {\n"
"    \n"
"    background-color: rgb(30, 203, 27);\n"
"    border: 2px  solid black;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    \n"
"    background-color: rgb(10, 186, 1);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    \n"
"    background-color: rgb(0, 255, 128);\n"
"}")
        self.pg1_addition_btn_3.setObjectName("pg1_addition_btn_3")
        self.pg1_addition_btn_4 = QtWidgets.QPushButton(parent=self.page_2)
        self.pg1_addition_btn_4.setGeometry(QtCore.QRect(1190, 690, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pg1_addition_btn_4.setFont(font)
        self.pg1_addition_btn_4.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(12, 44, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    background-color: rgb(0, 2, 147);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(75, 192, 255);\n"
"}")
        self.pg1_addition_btn_4.setObjectName("pg1_addition_btn_4")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1437, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcome_label.setText(_translate("MainWindow", "Welcome Chinu Bisht"))
        self.welcome_label_2.setText(_translate("MainWindow", "Start Test"))
        self.pg1_addition_btn.setText(_translate("MainWindow", "Addition"))
        self.pg1_subtraction_btn.setText(_translate("MainWindow", "Subtraction"))
        self.pg1_multi_btn.setText(_translate("MainWindow", "Multiplication"))
        self.pg1_division_btn.setText(_translate("MainWindow", "Division"))
        self.head_label.setText(_translate("MainWindow", "Addition Test"))
        self.welcome_label_5.setText(_translate("MainWindow", "   76\n"
"+ 34"))
        self.head_label_2.setText(_translate("MainWindow", "110"))
        self.welcome_label_8.setText(_translate("MainWindow", "   760\n"
"+ 314"))
        self.head_label_3.setText(_translate("MainWindow", "1074"))
        self.welcome_label_15.setText(_translate("MainWindow", "   76111\n"
"+ 34534"))
        self.head_label_15.setText(_translate("MainWindow", "1074"))
        self.pg1_addition_btn_2.setText(_translate("MainWindow", "Result"))
        self.welcome_label_7.setText(_translate("MainWindow", "   76\n"
"+ 34"))
        self.head_label_4.setText(_translate("MainWindow", "110"))
        self.welcome_label_12.setText(_translate("MainWindow", "   76\n"
"+ 34"))
        self.head_label_7.setText(_translate("MainWindow", "110"))
        self.welcome_label_16.setText(_translate("MainWindow", "   76\n"
"+ 34"))
        self.head_label_8.setText(_translate("MainWindow", "110"))
        self.welcome_label_17.setText(_translate("MainWindow", "   76\n"
"+ 34"))
        self.head_label_9.setText(_translate("MainWindow", "110"))
        self.welcome_label_13.setText(_translate("MainWindow", "   760\n"
"+ 314"))
        self.head_label_11.setText(_translate("MainWindow", "1074"))
        self.welcome_label_19.setText(_translate("MainWindow", "   760\n"
"+ 314"))
        self.head_label_14.setText(_translate("MainWindow", "1074"))
        self.pg1_addition_btn_3.setText(_translate("MainWindow", "Clear"))
        self.pg1_addition_btn_4.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
